<?php

/**
 * @file
 * Provides a thin wrapper for the Dropbox API.
 */

use \DropboxApp;
/**
 * Implements hook_permission.
 */
function dropbox_app_permission() {
  return array(
    'access dropbox app' => array(
      'title' => t('Access Dropbox App'),
      'description' => t('Allows some users to access the Dropbox App.'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function dropbox_app_libraries_info() {
  $libraries['dropbox_sdk'] = array(
    'name' => 'Dropbox API SDK',
    'vendor url' => 'https://www.dropbox.com/developers/core/sdks/php',
    'version arguments' => array(
      'file' => 'ChangeLog.txt',
      'pattern' => '/^(\d+)/',
      'lines' => 2,
    ),
    'files' => array(
      'php' => array('lib/Dropbox/autoload.php'),
    ),
  );

  return $libraries;
}
